name: Build Linux

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    strategy:
      matrix:
        os: ["ubuntu-latest"] # , 'macos-latest', 'windows-latest']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v6
        with:
          # Shallow clones should be disabled for a better relevancy of SonarQube analysis
          fetch-depth: 0
      # execute sonar:sonar only for internal PRs
      - name: Set Maven Additional Goals
        run: |
          echo "SONARGOAL=sonar:sonar" >> $GITHUB_ENV
        if: ${{ env.SONAR_TOKEN }}
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: "Set up Java"
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"

      - name: "Build, test, code quality and coverage"
        run: mvn verify -Pperformance-tests -Pjacoco $SONARGOAL -Dsonar.projectKey=LorenzoBettini_bart

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/target/surefire-reports/'
        if: failure() 
      
      - name: Archive JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: '**/target/site/jacoco/'
        if: always()

      - name: Run Mutation Testing
        run: mvn org.pitest:pitest-maven:mutationCoverage -Dpit-timeout-const=1000

      - name: Archive Mutation Testing Report
        uses: actions/upload-artifact@v4
        with:
          name: mutation-testing-report
          path: '**/target/pit-reports/'
        if: always()